package com.example.englishwordsapp.adminPanel

import com.example.englishwordsapp.data.model.QuizQuestionsResponse

object WordsForQuiz {
//    val listOfWords = mutableListOf(
//        QuizQuestionsResponse(3, "Car", listOf("Pişik", "Dondurma", "Şəhər", "Avtobus")),
//        QuizQuestionsResponse(3, "Ball", listOf("Qələm", "Kitab", "Dəftər", "Top")),
//        QuizQuestionsResponse(2, "Cat", listOf("Qapı", "Çanta", "Pişik", "Fincan")),
//        QuizQuestionsResponse(0, "Dog", listOf("İt", "Yol", "Stol", "Qar")),
//        QuizQuestionsResponse(1, "Elephant", listOf("Zurafə", "Fil", "Gül", "Qapı")),
//        QuizQuestionsResponse(3, "Fish", listOf("Stol", "Qələm", "Meyvə", "Balıq")),
//        QuizQuestionsResponse(0, "Green", listOf("Yaşıl", "Qırmızı", "Sarı", "Mavi")),
//        QuizQuestionsResponse(2, "House", listOf("At", "Kitab", "Ev", "Qapı")),
//        QuizQuestionsResponse(1, "Ice", listOf("Kitab", "Buz", "Ağac", "Dondurma")),
//        QuizQuestionsResponse(3, "Juice", listOf("Lampa", "Masa", "Çanta", "Şirə")),
//        QuizQuestionsResponse(0, "Kite", listOf("Uçurtma", "Pişik", "Balıq", "Kitab")),
//        QuizQuestionsResponse(2, "Lemon", listOf("Hand", "Stol", "Limon", "Dəftər")),
//        QuizQuestionsResponse(1, "Milk", listOf("Qapı", "Süd", "Telefon", "İt")),
//        QuizQuestionsResponse(0, "Night", listOf("Gecə", "Günəş", "Yumurta", "Qələm")),
//        QuizQuestionsResponse(3, "Orange", listOf("Mavi", "Limon", "Fil", "Portağal")),
//        QuizQuestionsResponse(0, "Pencil", listOf("Qələm", "Qar", "Günəş", "Top")),
//        QuizQuestionsResponse(2, "Queen", listOf("İt", "Qapı", "Kraliça", "Buz")),
//        QuizQuestionsResponse(1, "Red", listOf("Masa", "Qırmızı", "Sıra", "Telefon")),
//        QuizQuestionsResponse(2, "Apple", listOf("Şagird", "Armud", "Alma", "Ay")),
//        QuizQuestionsResponse(0, "Book", listOf("Kitab", "Çanta", "Yaşıl", "Telefon")),
//    )

//    val listOfElementaryWords = listOf(
//        QuizQuestionsResponse(0, "Airport", listOf("Hava Limanı", "Mağaza", "Kitab", "Meyvə")),
//        QuizQuestionsResponse(1, "Animal", listOf("Telefon", "Heyvan", "Çanta", "Gül")),
//        QuizQuestionsResponse(2, "Answer", listOf("Sual", "Fil", "Cavab", "Qələm")),
//        QuizQuestionsResponse(3, "Autumn", listOf("Çiçək", "Yol", "Qar", "Payız")),
//        QuizQuestionsResponse(0, "Beautiful", listOf("Gözəl", "İnsan", "Ev", "İt")),
//        QuizQuestionsResponse(1, "Bicycle", listOf("Qapı", "Velosiped", "Balıq", "Sandıq")),
//        QuizQuestionsResponse(2, "Birthday", listOf("Qələmlik", "Uçurtma", "Doğum günü", "Çay")),
//        QuizQuestionsResponse(3, "Breakfast", listOf("Qırmızı", "Pişik", "Balıq", "Səhər yeməyi")),
//        QuizQuestionsResponse(0, "Building", listOf("Bina", "Telefon", "Gül", "Dağ")),
//        QuizQuestionsResponse(1, "Butterfly", listOf("İt", "Kəpənək", "Velosiped", "Dəftər")),
//        QuizQuestionsResponse(2, "Ship", listOf("Ev", "Məktəb", "Gəmi", "Qələm")),
//        QuizQuestionsResponse(3, "Winter", listOf("Yay", "Kitab", "Balıq", "Qış")),
//        QuizQuestionsResponse(0, "Cheese", listOf("Pendir", "Yağ", "Qələm", "Buz")),
//        QuizQuestionsResponse(1, "Chicken", listOf("Qələm", "Toyuq", "Kitab", "Yumurta")),
//        QuizQuestionsResponse(2, "Circle", listOf("Ulduz", "Yol", "Dairə", "Sandıq")),
//        QuizQuestionsResponse(3, "Clothes", listOf("Pişik", "Qələm", "Dəftər", "Geyim")),
//        QuizQuestionsResponse(0, "Coffee", listOf("Qəhvə", "Yol", "Restoran", "Sandıq")),
//        QuizQuestionsResponse(1, "Country", listOf("Kitab", "Ölkə", "Şəhər", "Qitə")),
//        QuizQuestionsResponse(2, "Cow", listOf("Çiçək", "Bayquş", "İnək", "Qoyun")),
//        QuizQuestionsResponse(3, "Crowded", listOf("Qar", "Velosiped", "Ağac", "İzdiham")),
//        QuizQuestionsResponse(0, "Dangerous", listOf("Təhlükəli", "Asan", "Rahat", "Böyük")),
//        QuizQuestionsResponse(1, "Daughter", listOf("Ana", "Qız", "Nənə", "Nəvə")),
//        QuizQuestionsResponse(2, "Different", listOf("Ev", "Eyni", "Fərqli", "Kiçik")),
//        QuizQuestionsResponse(3, "Dinner", listOf("Toyuq", "Uçurtma", "Çay", "Şam yeməyi")),
//        QuizQuestionsResponse(0, "Doctor", listOf("Həkim", "Polis", "Hakim", "Meyvə")),
//        QuizQuestionsResponse(1, "Money", listOf("Velosiped", "Pul", "Məktəb", "Kitab")),
//        QuizQuestionsResponse(2, "Giraffe", listOf("Gəmi", "Telefon", "Zürafə", "Çiçək")),
//        QuizQuestionsResponse(3, "Evening", listOf("Pişik", "Dəftər", "Səhər", "Axşam")),
//        QuizQuestionsResponse(0, "Excited", listOf("Həyəcanlı", "Qorxulu", "Balıq", "Gözəl")),
//        QuizQuestionsResponse(1, "Expensive", listOf("Ucuz", "Bahalı", "Çanta", "Ev")),
//        QuizQuestionsResponse(2, "Family", listOf("Velosiped", "Qapı", "Ailə", "Soyad")),
//        QuizQuestionsResponse(3, "Surname", listOf("Kitab", "Ad", "Ağac", "Soyad")),
//        QuizQuestionsResponse(0, "Lake", listOf("Göl", "Dəniz", "Çay", "Ləkə")),
//        QuizQuestionsResponse(1, "Flower", listOf("Günəş", "Gül", "Çanta", "Yol")),
//        QuizQuestionsResponse(2, "Friend", listOf("Qapı", "Balıq", "Dost", "Çiçək")),
//        QuizQuestionsResponse(3, "Fruit", listOf("Pişik", "Gəmi", "Dəftər", "Meyvə")),
//        QuizQuestionsResponse(0, "Garden", listOf("Bağ", "Çanta", "Bulud", "Qələm")),
//        QuizQuestionsResponse(1, "Holiday", listOf("Kitab", "Tətil", "Dəniz", "Məktəb")),
//        QuizQuestionsResponse(1, "Spring", listOf("Qış", "Bahar", "Otel", "Hovuz")),
//        QuizQuestionsResponse(0, "Summer", listOf("Yay", "İsti", "Dəniz", "Payız")),
//        QuizQuestionsResponse(2, "Horse", listOf("Ev", "Bina", "At", "Məktəb")),
//        QuizQuestionsResponse(3, "Bird", listOf("Kitab", "Meymun", "Çörək", "Quş")),
//        QuizQuestionsResponse(2, "Monkey", listOf("Pul", "Dağ", "Meymun", "Ay")),
//        QuizQuestionsResponse(3, "Hand", listOf("Ayaq", "Bel", "Barmaq", "Əl")),
//        QuizQuestionsResponse(0, "Finger", listOf("Barmaq", "Ayaq", "Böyük", "Fincan")),
//    )

    val listOfIntermediateWords = listOf(
        QuizQuestionsResponse(1, "Community", listOf("İlişki", "Toplum", "Detal", "Qismət")),
        QuizQuestionsResponse(1, "Random", listOf("Rəqəm", "Təsadüfi", "Yaranmaq", "Təkrar")),
        QuizQuestionsResponse(0, "Range", listOf("Aralıq", "Hərəkət", "Nüfuz", "Söz")),
        QuizQuestionsResponse(3, "Reinforce", listOf("Yağış", "Nəfər", "Yaranmaq", "Təqviyə")),
        QuizQuestionsResponse(0, "Reject", listOf("Ləğv", "Xəbər", "Yaranmaq", "Saxlamaq")),
        QuizQuestionsResponse(1, "Release", listOf("Yaratmaq", "Buraxmaq", "Təkrar", "Söz")),
        QuizQuestionsResponse(2, "Reliable", listOf("Davamlı", "Mürəkkəb", "Etibarlı", "Sadə")),
        QuizQuestionsResponse(3, "Resident", listOf("Müvəqqəti", "Xəbər", "Prezident", "Sakin")),
        QuizQuestionsResponse(0, "Restrain", listOf("Saxlamaq", "Buraxmaq", "Qaldırmaq", "Əsdirmək")),
        QuizQuestionsResponse(1, "Restrict", listOf("Xəbərdarlıq", "Məhdudlaşdırmaq", "Yay", "İzn")),
        QuizQuestionsResponse(2, "Reveal", listOf("Saxlı", "Xəbər", "Aşkar", "Gizli")),
        QuizQuestionsResponse(3, "Visdom", listOf("Məzmun", "Savadlı", "Alicənab", "Müdrik")),
        QuizQuestionsResponse(0, "Simulate", listOf("Təqlid", "Ağlamaq", "Böyütmək", "Gecikmək")),
        QuizQuestionsResponse(1, "Solar", listOf("Fərq", "Günəşli", "Aylı", "Küləkli")),
        QuizQuestionsResponse(2, "Specify", listOf("İtirmək", "Silmək", "Müəyyənləşdirmək", "Tamamlamaq")),
        QuizQuestionsResponse(3, "Dot", listOf("Planlaşdırmaq", "Boşluq", "Vergül", "Nöqtə")),
        QuizQuestionsResponse(0, "Reverse", listOf("Tərs", "Yuxarı", "Əyri", "Düz")),
        QuizQuestionsResponse(1, "Straight", listOf("Əyri", "Düz", "Aşağı", "Böyük")),
        QuizQuestionsResponse(2, "Injury", listOf("Əvəz etmək", "Dəyişmək", "Zədə", "Sağalmaq")),
        QuizQuestionsResponse(3, "Suspend", listOf("Gözləmək", "Əymək", "Davam", "Dayandırmaq")),
        QuizQuestionsResponse(0, "Universe", listOf("Kainat", "Planet", "Ulduz", "Ay")),
        QuizQuestionsResponse(1, "Target", listOf("Dairə", "Hədəf", "Götürmək", "Alçaq")),
        QuizQuestionsResponse(2, "Terminate", listOf("Qətl", "Başlamaq", "Bitirmək", "Dondurmaq")),
        QuizQuestionsResponse(3, "Theme", listOf("Temizlik", "Kağız", "Başlıq", "Mövzu")),
        QuizQuestionsResponse(2, "Transition", listOf("Qorxu", "Qaçmaq", "Keçid", "Susmaq")),
        QuizQuestionsResponse(0, "Transparent", listOf("Şəffaf", "Tədbir", "Valideyin", "Qara")),
        QuizQuestionsResponse(0, "Trend", listOf("İrəliləyiş", "Ənənəvi", "Köhnə", "Digər")),
        QuizQuestionsResponse(2, "Equal", listOf("Sərbəst", "Ekvator", "Bərabər", "Ayrı")),
        QuizQuestionsResponse(3, "Utilize", listOf("Bitirmək", "Bayram", "Yarılamaq", "İstifadə etmək")),
        QuizQuestionsResponse(0, "Vehicle", listOf("Nəqliyyat", "Gümüş", "Yaş", "Torpaq")),
        QuizQuestionsResponse(1, "Version", listOf("Növ", "Versiya", "Növbəti", "Qısa")),
        QuizQuestionsResponse(2, "Via", listOf("Arxasında", "Ətraf", "Vasitəsilə", "Məhdud")),
        QuizQuestionsResponse(0, "Vision", listOf("Görmə", "Vasitə", "Aralıq", "Ortaq")),
        QuizQuestionsResponse(1, "Volume", listOf("Xırda", "Həcm", "Çəki", "En")),
        QuizQuestionsResponse(2, "Whereas", listOf("Hələki", "Lakin", "Halbuki", "Harada")),
        QuizQuestionsResponse(3, "Widespread", listOf("Qısacası", "Ətrafda", "Daxildə", "Geniş yayılmış")),
        QuizQuestionsResponse(0, "Yield", listOf("Məhsul", "Tərəvəz", "Gözlük", "Qara")),
        QuizQuestionsResponse(1, "Abstract", listOf("Yeganə", "Mücərrəd", "Tək", "Çoxluq")),
        QuizQuestionsResponse(2, "Accumulate", listOf("Ayırmaq", "Bölmək", "Toplamaq", "Yığışdırmaq")),
        QuizQuestionsResponse(1, "Append", listOf("Silmək", "Əlavə etmək", "Çözmək", "Sarımaq")),
        QuizQuestionsResponse(3, "Automate", listOf("Əvəzləmək", "Təmir etmək", "Anlamaq", "Avtomatlaşdırmaq")),
        QuizQuestionsResponse(0, "Bias", listOf("Qərəzlik", "Yumuşaq", "Mehriban", "Kobud")),
        QuizQuestionsResponse(2, "Bulk", listOf("Böyük", "Kiçik", "Toplu", "Həcm")),
        QuizQuestionsResponse(3, "Cease", listOf("Kəsmək", "Dondurmaq", "Davam etdirmək", "Dayandırmaq")),
        QuizQuestionsResponse(1, "Concurrent", listOf("Eyni", "Paralel", "Rəqib", "Düşmən")),
        QuizQuestionsResponse(0, "Confirm", listOf("Təstiq etmək", "İcazə", "İcazə Almaq", "Yetgin")),
        QuizQuestionsResponse(1, "Contemporary", listOf("Mövcud", "Müasir", "Fərqli", "Qara")),
        QuizQuestionsResponse(2, "Contradiction", listOf("Qəti", "Eyni", "Ziddiyyət", "Mübahisə")),
        QuizQuestionsResponse(1, "Converse", listOf("Əks", "Müzakirə", "Hündür", "Razılaşmaq")),
        QuizQuestionsResponse(2, "Convey", listOf("Bölmək", "Geri almaq", "Ötürmək", "Yandırmaq")),
        QuizQuestionsResponse(0, "Defect", listOf("Qüsur", "Tam", "Zərər", "Fərdi")),
        QuizQuestionsResponse(1, "Deficiency", listOf("Nöqsan", "Çatışmamazlıq", "Yarım", "Qısa")),
        QuizQuestionsResponse(3, "Devise", listOf("Yetiştirmək", "Böyütmək", "Silmək", "Hazırlamaq")),
        QuizQuestionsResponse(2, "Destroy", listOf("Əzmək", "Tədbir", "Dağıtmaq", "Sıxmaq")),
        QuizQuestionsResponse(3, "Duration", listOf("Yarım", "Bölgü", "Bütov", "Davametmə")),
        QuizQuestionsResponse(0, "Define", listOf("Müəyyənləşdirmək", "İtirmək", "Qaçırtmaq", "Qalmaq")),
        QuizQuestionsResponse(3, "Excellent", listOf("Pis", "Yaxşı", "Kafi", "Möhtəşəm")),
        QuizQuestionsResponse(0, "Forgot", listOf("Unutmaq", "Razılaşmaq", "İmtina", "Böyümək")),
        QuizQuestionsResponse(1, "Frost", listOf("Buz", "Şaxta", "Soyuducu", "Dondurma")),
        QuizQuestionsResponse(2, "Framework", listOf("Qutu", "Masa", "Çərçivə", "Ayna")),
        QuizQuestionsResponse(3, "Guideline", listOf("Göstəriş", "İtkin", "Ağır", "Təlimat")),
        QuizQuestionsResponse(0, "Hero", listOf("Qəhrəman", "Vergi", "Döyüşçü", "Əsgər")),
        QuizQuestionsResponse(1, "Hypothesis", listOf("Fakt", "Fərziyyə", "İnanc", "Müxtəlif")),
        QuizQuestionsResponse(3, "Immortal", listOf("Sonsuz", "Tək", "Böyük", "Ölümsüz")),
        QuizQuestionsResponse(0, "Inspiration", listOf("Ilham", "Təsəlli", "Qərar", "Yekun")),
        QuizQuestionsResponse(2, "Infinity", listOf("Sadəlik", "Avtomobil", "Sonsuzluq", "Səma")),
        QuizQuestionsResponse(2, "Isolate", listOf("Birləşdirmək", "Tədbir", "Təcrid", "Toplamaq")),
        QuizQuestionsResponse(3, "Layer", listOf("Sütun", "Bölgü", "Kəlmə", "Qat")),
        QuizQuestionsResponse(0, "Medium", listOf("Orta", "Kiçik", "Böyük", "Ara")),
        QuizQuestionsResponse(1, "Walk", listOf("Divar", "Gəzmək", "Qaçmaq", "Uçmaq")),
        QuizQuestionsResponse(2, "Swim", listOf("Uçmaq", "Sürünmək", "Üzmək", "Gəzmək")),
        QuizQuestionsResponse(3, "Wall", listOf("Gəzmək", "Zirzəmi", "Qapı", "Divar")),
        QuizQuestionsResponse(3, "Talk", listOf("Susmaq", "Dindirmək", "Dinləmək", "Danışmaq")),
        QuizQuestionsResponse(0, "Speak", listOf("Danışmaq", "Dindirmək", "Dinləmək", "Susmaq")),
        QuizQuestionsResponse(1, "Listen", listOf("Danışmaq", "Dinləmək", "Səssizlik", "Susmaq")),
        QuizQuestionsResponse(2, "Write", listOf("Başlamaq", "Dindirmək", "Yazmaq", "Sarımaq")),
        QuizQuestionsResponse(2, "Understand", listOf("Başlamaq", "Bilməmək", "Anlamaq", "Bitirmək")),
    )

    val listFoAdvanceLevelWordsForQuiz = listOf(
        QuizQuestionsResponse(0, "Abate", listOf("Azalma", "Məğlubiyyət", "Sakitləşdirmək", "Ümumi")),
        QuizQuestionsResponse(2, "Abhor", listOf("Həzz", "Narahatçılıq", "Nifrət", "Düşmənlik")),
        QuizQuestionsResponse(0, "Accolade", listOf("Tərif", "Ehtiram", "Əfsus", "Saxlamaq")),
        QuizQuestionsResponse(1, "Acrimonious", listOf("Münasibətsiz", "Kəskin", "Kəsilik", "Mübarizə")),
        QuizQuestionsResponse(2, "Acumen", listOf("Bolluq", "Təbiiyyət", "Idrak", "Səmimiyyət")),
        QuizQuestionsResponse(3, "Admonish", listOf("Nizam", "Bədbəxtlik", "Öyüd-nəsihət", "Bənzərsiz")),
        QuizQuestionsResponse(0, "Adulation", listOf("Tərif", "Nəqəd", "Nifrət", "Səmimiyyət")),
        QuizQuestionsResponse(1, "Adversity", listOf("Zəhmət", "Müsibət", "Lüks", "Qalib")),
        QuizQuestionsResponse(2, "Aesthetic", listOf("Gözəllik", "Təbiiyyət", "Estetik", "Kəskinlik")),
        QuizQuestionsResponse(3, "Affable", listOf("Sadiq", "Düşmənlik", "Məhəbbət", "Mehriban")),
        QuizQuestionsResponse(0, "Affluent", listOf("Varlı", "Nəzərdən keçirmək", "İnkişaf", "Üstünlük")),
        QuizQuestionsResponse(1, "Aggrandize", listOf("Zənginləşmək", "Böyütmək", "Müvəffəqiyyət", "Məzmun")),
        QuizQuestionsResponse(0, "Alacrity", listOf("Cəldlik", "Qəzəb", "Dəqiq", "Hiss")),
        QuizQuestionsResponse(1, "Altruistic", listOf("Müharibə", "Fədakar", "Səmimiyyət", "Zərif")),
        QuizQuestionsResponse(2, "Amalgamate", listOf("Birlikdə", "Qanun", "Birləşmək", "Müqəddəs")),
        QuizQuestionsResponse(3, "Ambivalent", listOf("Müəllim", "Gizli", "İkitərəfli", "Ünsiyyət")),
        QuizQuestionsResponse(0, "Ameliorate", listOf("Yaxşılaşdırmaq", "Əlil", "Kəskinlik", "Dolma")),
        QuizQuestionsResponse(2, "Analogous", listOf("Oz", "Təəssüf", "Analoji", "Güclü")),
        QuizQuestionsResponse(2, "Apathetic", listOf("Bil", "Şübhəli", "Laqeyd", "Məhəbbət")),
        QuizQuestionsResponse(0, "Appease", listOf("Sakitləşdirmək", "Səmimiyyət", "Zənnə", "Çox görmək")),
        QuizQuestionsResponse(1, "Arbitrary", listOf("Şəxsi", "İxtiyari", "Xoşbəxtlik", "Nəsillə")),
        QuizQuestionsResponse(2, "Arcane", listOf("Gizlilik", "Lavrov", "Gizli", "Mənbə")),
        QuizQuestionsResponse(0, "Ardent", listOf("Alovlu", "Zövq", "Uğur", "Azot")),
        QuizQuestionsResponse(1, "Arduous", listOf("Fərdi", "Çətin", "Nüfuz", "Ciddi")),
        QuizQuestionsResponse(3, "Assiduous", listOf("Dövlət", "Lagman", "Kəskinlik", "Çalışqan")),
        QuizQuestionsResponse(0, "Astute", listOf("Zəkalı", "Aqil", "Zəngin", "Üstün")),
        QuizQuestionsResponse(2, "Attenuate", listOf("Kiçiltmək", "Həssaslaşdırmaq", "Zəiflətmək", "Aşağı düşürmək")),
        QuizQuestionsResponse(3, "Audacious", listOf("Qorxaq", "Qətiyyən", "Sərəncam", "Cəsarətli")),
        QuizQuestionsResponse(0, "Augment", listOf("Artırmaq", "Genişlətmək", "Böyütmək", "Tərəqqi")),
        QuizQuestionsResponse(0, "Auspicious", listOf("Xeyirli", "Barədə", "Gözəl", "Əladır")),
        QuizQuestionsResponse(1, "Austere", listOf("Ciddi", "Sərt", "Qurucu", "Qət-qurucu")),
        QuizQuestionsResponse(2, "Autonomous", listOf("Müstəqil", "İstifadəçi", "Muxtar", "Faydalı")),
        QuizQuestionsResponse(3, "Avarice", listOf("Əsasən", "Məhrum", "Yalnızca", "Xəsis")),
        QuizQuestionsResponse(1, "Benevolent", listOf("Soyuq", "Xeyirxah", "Qardaş", "Sevgi")),
        QuizQuestionsResponse(2, "Benign", listOf("Xəstəlik", "Fəsad", "Xeyirxah", "Zərər")),
        QuizQuestionsResponse(3, "Buttress", listOf("Qoruyucu", "Dəstək", "Sərbəst", "Bağlayıcı")),
        QuizQuestionsResponse(1, "Callous", listOf("Ədalət", "Mərhəmətsiz", "Böyüklük", "Düşmənlik")),
        QuizQuestionsResponse(2, "Candor", listOf("Cəsur", "İcazə", "Açıq-aşkar", "Qətiyyət")),
        QuizQuestionsResponse(3, "Capricious", listOf("Dəyişmək", "Yenilik", "Zəif", "Şıltaq")),
        QuizQuestionsResponse(3, "Censure", listOf("Əhval", "Əlaqə", "Böyük", "Qınaq")),
        QuizQuestionsResponse(0, "Chicanery", listOf("Dələduzluq", "Hökumət", "Hüquqi", "Fəaliyyət")),
        QuizQuestionsResponse(2, "Circumscribe", listOf("Məlumat", "Fərziyyə", "Məhdud", "Fayda")),
        QuizQuestionsResponse(3, "Circumspect", listOf("Təhlükəsiz", "Bəzi", "Qısa", "Ehtiyatlı")),
        QuizQuestionsResponse(1, "Clandestine", listOf("Qalmaqal", "Gizli", "Qulluq", "Yayımlanmış")),
        QuizQuestionsResponse(2, "Coalesce", listOf("Təşəbbüs", "Geri", "Birləşmək", "Qalib")),
        QuizQuestionsResponse(3, "Cogent", listOf("Yalan", "Çox", "Zor", "İnandırıcı")),
        QuizQuestionsResponse(1, "Commensurate", listOf("Müqayisəli", "Mütənasib", "Zəif", "Zaman")),
        QuizQuestionsResponse(2, "Complacent", listOf("Bəxtiyyar", "İddia", "Özündən razı", "Yeniləmə")),
        QuizQuestionsResponse(0, "Conciliatory", listOf("Barışdırıcı", "Xəbər", "Araşdırma", "Gözəllik")),
        QuizQuestionsResponse(1, "Confluence", listOf("Müqavimət", "Birləşmə", "Mənfi", "Yaddaş")),
        QuizQuestionsResponse(2, "Conflagration", listOf("Zərər", "Görünmək", "Yanğın", "Təbii")),
        QuizQuestionsResponse(0, "Conjecture", listOf("Zənn", "Kütlə", "Dəstə", "Tərəzi")),
        QuizQuestionsResponse(0, "Consternation", listOf("Çaşqınlıq", "Xeyir", "Xərclər", "Dünya")),
        QuizQuestionsResponse(0, "Construe", listOf("Təfsir etmək", "Xəritə", "Səyahət", "Həvəs")),
        QuizQuestionsResponse(0, "Contentious", listOf("Mübahisəli", "Münaqişə", "Müraciət", "Məlumat")),
        QuizQuestionsResponse(0, "Contrite", listOf("Təssüf", "Məqsəd", "Məlumat", "Tərcümə")),
        QuizQuestionsResponse(0, "Copious", listOf("Bol", "Yeniləmə", "Yoxlamaq", "Açmaq")),
        QuizQuestionsResponse(0, "Corroborate", listOf("Təsdiq", "Zəhmət", "Yerləşmə", "Tərəzi")),
        QuizQuestionsResponse(0, "Credulous", listOf("Etibarlı", "Səbəb", "Sahə", "Təhlükəsiz")),
        QuizQuestionsResponse(0, "Culpable", listOf("Günahkar", "Qərar", "Qorunmaq", "Zəmanət")),
        QuizQuestionsResponse(0, "Dearth", listOf("Çatışmamazlıq", "Kəşf", "Kontrol", "Yaranma")),
        QuizQuestionsResponse(0, "Debilitate", listOf("Zəifləmə", "Qazanmaq", "Qarışıq", "Dəstək")),
        QuizQuestionsResponse(0, "Debunk", listOf("İfşa", "Əks", "Mərhəmətsiz", "Məhrum")),
        QuizQuestionsResponse(0, "Decorum", listOf("Ədəb", "Qurucu", "Qızıl", "Zəmanət")),
        QuizQuestionsResponse(0, "Deference", listOf("Ehtiram", "Ədalət", "Ədalət", "Gözəllik")),
        QuizQuestionsResponse(0, "Deleterious", listOf("Zərərli", "Mənfəət", "Təhlükə", "Xoş")),
        QuizQuestionsResponse(0, "Demur", listOf("Narazı olmaq", "Sorğu", "İstəmək", "Müraciət")),
        QuizQuestionsResponse(0, "Denizen", listOf("Sakin", "Müştəri", "Təhlükə", "Birləşmə")),
        QuizQuestionsResponse(0, "Deride", listOf("Lağ etmək", "Sağalmaq", "Salamlaşmaq", "Təzələmək")),
        QuizQuestionsResponse(0, "Derivative", listOf("Törəmə", "Ziyarət", "Zədələmək", "Qadağa")),
        QuizQuestionsResponse(0, "Diffident", listOf("Özgüvənsiz", "Təhlükəsiz", "Müraciət", "Hələ")),
        QuizQuestionsResponse(0, "Dilatory", listOf("Ləng", "Gecikmək", "Təhlükəsiz", "Bədbəxt")),
        QuizQuestionsResponse(0, "Disaffected", listOf("Narazı", "Zədələnmiş", "Mərhəmət", "Xəbərdar")),
        QuizQuestionsResponse(0, "Discern", listOf("Fərqləndirən", "Görmək", "Ayrı", "Araşdırma")),
        QuizQuestionsResponse(0, "Discomfit", listOf("Narahatlıq", "Bədbəxtlik", "Qorunmaq", "Tənqid")),
        QuizQuestionsResponse(0, "Disdain", listOf("Nifrət etmək", "Xeyir", "Qəbul", "Səbr")),
        QuizQuestionsResponse(2, "Disingenuous", listOf("Zinətləndirmək", "Qoşulma", "Səmimi olmayan", "Yığma")),
        QuizQuestionsResponse(2, "Disseminate", listOf("Duyğu", "Şərəf", "Yaymaq", "Qurtarmaq")),
        QuizQuestionsResponse(2, "Distend", listOf("Üstün", "Güzəştləmək", "Doldurulmuş", "Tələbə")),
        QuizQuestionsResponse(2, "Dormant", listOf("Yad", "Mənşə", "Yatmış", "Aşağı")),
        QuizQuestionsResponse(2, "Duress", listOf("Təmiz", "Mükafat", "Məcbur etmək", "Həftə")),
        QuizQuestionsResponse(2, "Ebullient", listOf("Bərabərlik", "Birlikdə", "Qaynayan", "Almaq")),
        QuizQuestionsResponse(2, "Edifice", listOf("Ağrı", "Mükəmməl", "Bina", "Nümayiş")),
        QuizQuestionsResponse(2, "Efficacy", listOf("Əsas", "Zorlamaq", "Effektivlik", "Mən")),
        QuizQuestionsResponse(2, "Elicit", listOf("Kapital", "Köhnə", "Aşkar etmək", "Sahib")),
        QuizQuestionsResponse(2, "Elucidate", listOf("Quruluş", "Gəmilər", "Aydınlaşdırmaq", "Günahkar")),
        QuizQuestionsResponse(2, "Embellish", listOf("Yaxşı", "Mədəniyyət", "Zinətləndirmək", "Tövsiyyə")),
        QuizQuestionsResponse(2, "Eminent", listOf("Qazanmaq", "Xidmət", "Görkəmli olmaq", "Əlil")),
        QuizQuestionsResponse(2, "Emulate", listOf("Siyasət", "Müdafiə", "Təqlid etmək", "Etmək")),
        QuizQuestionsResponse(2, "Engender", listOf("Millət", "Dəstə", "Yaratmaq", "Yanıt")),
        QuizQuestionsResponse(2, "Enigmatic", listOf("Xahiş", "Birgə", "Müəmmalı", "Bütün")),
        QuizQuestionsResponse(2, "Equivocate", listOf("Yaxın", "Gözəllik", "İkimənalı", "İstifadə")),
        QuizQuestionsResponse(2, "Erudite", listOf("Müsahibə", "Kifayət", "Savadlı", "Xahiş")),
        QuizQuestionsResponse(2, "Eulogy", listOf("Qayğı", "Məşhur", "Tərifləmək", "Dəyər")),
        QuizQuestionsResponse(2, "Evanescent", listOf("Düşünmək", "Böyük", "Ani", "Qurtarmaq")),
        QuizQuestionsResponse(2, "Exacerbate", listOf("Müşahidə", "Əlçatan", "Kəskinləşdirmək", "Kiçiltmək")),
        QuizQuestionsResponse(2, "Exculpate", listOf("Ağartmaq", "Məğlub", "Bəraət", "Sərxoş olmaq")),
        QuizQuestionsResponse(2, "Exonerate", listOf("Əfsus", "Düşüncə", "Bəraət vermək", "Təbii")),
        QuizQuestionsResponse(2, "Exorbitant", listOf("Arıqlatmaq", "Ədalət", "Aşırı", "Öhdəlik")),
        QuizQuestionsResponse(2, "Expedient", listOf("Məhz", "Üstün", "Məqsədəuyğun", "Çatışmamaq")),
        QuizQuestionsResponse(2, "Extol", listOf("Dərin", "Əlçatan", "Tərifləmək", "Bəlkə")),
        QuizQuestionsResponse(2, "Extraneous", listOf("Düzəltilmiş", "Birbaşa", "Kənar", "Qışqırmaq")),
        QuizQuestionsResponse(1, "Extricate", listOf("Azad", "Qurtulmaq", "Cavab", "Gücü")),
        QuizQuestionsResponse(1, "Exult", listOf("Qalib", "Sevinmək", "Sənədləmək", "Mümkün")),
        QuizQuestionsResponse(1, "Facetious", listOf("Aşağılamaq", "Zarafatçıl", "Elçi", "Hərbi")),
        QuizQuestionsResponse(1, "Fallacious", listOf("Dolay", "Yanlış", "Alay", "Görmək")),
        QuizQuestionsResponse(1, "Fatuous", listOf("Öyrənmək", "Axmaq", "Özgə", "Gedir")),
        QuizQuestionsResponse(1, "Feckless", listOf("Açıq", "Məsuliyyətsiz", "Ağır", "Çox")),
        QuizQuestionsResponse(1, "Felicitous", listOf("Xatirə", "Uğurlu", "Ötürmək", "Ölkə")),
        QuizQuestionsResponse(1, "Fervid", listOf("Fəaliyyət", "Qızğın", "Görülmək", "Bağlı")),
        QuizQuestionsResponse(1, "Fetid", listOf("Kompüter", "İylənmiş", "Gələn", "Qaygılı")),
        QuizQuestionsResponse(1, "Florid", listOf("Ləzzətli", "Çiçəkli", "Tövsiyyə", "Rox")),
        QuizQuestionsResponse(1, "Foment", listOf("Yaşam", "Qıcıqlandırmaq", "Əsla", "Qalan")),
        QuizQuestionsResponse(1, "Frenetic", listOf("Bəs", "Çılğın", "Düşünmək", "Gedir")),
        QuizQuestionsResponse(1, "Garrulous", listOf("Mükəmməl", "Danışqan", "Müşahidə", "Sərəncam")),
        QuizQuestionsResponse(1, "Germane", listOf("Ağır", "Uyğun", "Müxtəlif", "Gedir")),
        QuizQuestionsResponse(1, "Gregarious", listOf("Səhvlər", "Ünsiyyətçil", "Təklif", "Rox")),
        QuizQuestionsResponse(1, "Guile", listOf("Düşünmək", "Hiylə", "Rəhbər", "Görmək")),
        QuizQuestionsResponse(1, "Hegemony", listOf("Qarşıdakı", "Hegemonluq", "Səbəb", "Etiraf")),
        QuizQuestionsResponse(1, "Heretic", listOf("Etmək", "Bidətçi", "Ölkə", "Tövsiyyə")),
        QuizQuestionsResponse(1, "Hiatus", listOf("Aralıq", "Fasilə", "Əsas", "Tərəf")),
        QuizQuestionsResponse(1, "Hierarchy", listOf("Müasir", "İyerarxiya", "Birlikdə", "Eyni")),
        QuizQuestionsResponse(3, "Ignominious", listOf("Cavab", "Tənqidləmək", "Xahiş", "Alçaq")),
        QuizQuestionsResponse(3, "Immutable", listOf("Xəyal", "Bəlkə", "Düzəltmə", "Dəyişməz")),
        QuizQuestionsResponse(3, "Imperious", listOf("İsti", "Rahat", "Müvəqqəti", "Hökmlü")),
        QuizQuestionsResponse(3, "Implacable", listOf("İlk", "Əvvəl", "Könül", "Barışmaz")),
        QuizQuestionsResponse(3, "Impugn", listOf("Səslənmək", "Yeganə", "Birlik", "Mübahisəli")),
        QuizQuestionsResponse(3, "Indolent", listOf("Ağla", "Qeyri", "Üzgü", "Tənbəl")),
        QuizQuestionsResponse(3, "Innocuous", listOf("Həmişə", "Əsəbi", "Fərqli", "Məsum")),
        QuizQuestionsResponse(3, "Insipid", listOf("Mümkün", "Gəlirli", "Araşdırma", "Zövqsüz")),
        QuizQuestionsResponse(3, "Invective", listOf("Düzgün", "Hərbi", "Sorğu", "Təhqiramiz")),
        QuizQuestionsResponse(3, "Irascible", listOf("Bədən", "Araşdırma", "Müşahidə", "Əsəbi")),
        QuizQuestionsResponse(3, "Itinerant", listOf("Sürət", "Başqa", "İşləri", "Səyahətçi")),
        QuizQuestionsResponse(3, "Lassitude", listOf("Qoymaq", "Səbəbi", "Açıqlama", "Yorğunluq")),
        QuizQuestionsResponse(3, "Latent", listOf("Hərbi", "Düzgün", "Səhv", "Gizli")),
        QuizQuestionsResponse(3, "Loquacious", listOf("Məktub", "Müxtəlif", "Təyinatı", "Danışqan")),
        QuizQuestionsResponse(3, "Lucid", listOf("Dərin", "Zaman", "Xatırlama", "Aydın")),
        QuizQuestionsResponse(3, "Luminous", listOf("Söhbət", "Yanılmaz", "Sevinc", "Işıqlı")),
        QuizQuestionsResponse(3, "Mendacious", listOf("İsti", "Kimi", "Daimi", "Xəyanətkar")),
        QuizQuestionsResponse(3, "Meticulous", listOf("Ənənəvi", "Köhnə", "Alman", "Vasvası")),
        QuizQuestionsResponse(3, "Misanthrope", listOf("Birbaşa", "Əsəbi", "Yuxulu", "Misantrop")),
        QuizQuestionsResponse(3, "Mitigate", listOf("Baxış", "Yalnız", "Yanılmaz", "Yumşaltmaq")),
        QuizQuestionsResponse(3, "Mollify", listOf("Qalib", "Yoxsulluq", "Xoşbəxt", "Yumşaltmaq")),
        QuizQuestionsResponse(3, "Munificent", listOf("Qalib", "Əvvəl", "Əliaçıq", "Xahiş"))
    )


}