package com.example.englishwordsapp.adminPanel

import com.example.englishwordsapp.data.model.QuizQuestionsResponse
import com.example.englishwordsapp.ui.main.learn.quiz.SimpleWordsModel

object WordsForVocabulary {

    val listOfWords = mutableListOf(
        SimpleWordsModel("Apple", "Alma", "[ˈæpl]", "noun", "beginner_level"),
        SimpleWordsModel("Car", "Avtomobil", "[kɑːr]", "noun", "beginner_level"),
        SimpleWordsModel("Cat", "Pişik", "[kæt]", "noun", "beginner_level"),
        SimpleWordsModel("Dog", "It", "[dɔg]", "noun", "beginner_level"),
        SimpleWordsModel("Table", "Masa", "[ˈteɪbəl]", "noun", "beginner_level"),
        SimpleWordsModel("Room", "Otaq", "[ruːm]", "noun", "beginner_level"),
        SimpleWordsModel("Door", "Qapı", "[dɔr]", "noun", "beginner_level"),
        SimpleWordsModel("Star", "Ulduz", "[stɑːr]", "noun", "beginner_level"),
        SimpleWordsModel("Sun", "Günəş", "[sʌn]", "noun", "beginner_level"),
        SimpleWordsModel("Pen", "Qələm", "[pɛn]", "noun", "beginner_level"),
        SimpleWordsModel("Book", "Kitab", "[bʊk]", "noun", "beginner_level"),
        SimpleWordsModel("Ice", "Buz", "[aɪs]", "noun", "beginner_level"),
        SimpleWordsModel("Mother", "Ana", "[ˈmʌðər]", "noun", "beginner_level"),
        SimpleWordsModel("Father", "Ata", "[ˈfɑːðər]", "noun", "beginner_level"),
        SimpleWordsModel("Brother", "Qardaş", "[ˈbrʌðər]", "noun", "beginner_level"),
        SimpleWordsModel("Phone", "Telefon", "[foʊn]", "noun", "beginner_level"),
        SimpleWordsModel("Bus", "Avtobus", "[bʌs]", "noun", "beginner_level"),
        SimpleWordsModel("School", "Məktəb", "[skuːl]", "noun", "beginner_level"),
        SimpleWordsModel("City", "Şəhər", "[ˈsɪti]", "noun", "beginner_level"),
        SimpleWordsModel("Cheese", "Pendir", "[ʧiz]", "noun", "beginner_level")
    )

    val listOfElementaryWords = mutableListOf(
        SimpleWordsModel("Happy", "Xoşbəxt", "[ˈhæpi]", "adjective", "elementary_level"),
        SimpleWordsModel("Run", "Qaçmaq", "[rʌn]", "verb", "elementary_level"),
        SimpleWordsModel("Big", "Böyük", "[bɪg]", "adjective", "elementary_level"),
        SimpleWordsModel("Jump", "Tullanmaq", "[ʤʌmp]", "verb", "elementary_level"),
        SimpleWordsModel("Blue", "Mavi", "[bluː]", "adjective", "elementary_level"),
        SimpleWordsModel("Eat", "Yemək", "[iːt]", "verb", "elementary_level"),
        SimpleWordsModel("Small", "Kiçik", "[smɔːl]", "adjective", "elementary_level"),
        SimpleWordsModel("Write", "Yazmaq", "[raɪt]", "verb", "elementary_level"),
        SimpleWordsModel("Fast", "Sürətli", "[fæst]", "adjective", "elementary_level"),
        SimpleWordsModel("Read", "Oxumaq", "[riːd]", "verb", "elementary_level"),
        SimpleWordsModel("Red", "Qırmızı", "[rɛd]", "adjective", "elementary_level"),
        SimpleWordsModel("Sing", "Oxumaq", "[sɪŋ]", "verb", "elementary_level"),
        SimpleWordsModel("Tall", "Hündür", "[tɔːl]", "adjective", "elementary_level"),
        SimpleWordsModel("Dance", "Rəqs etmək", "[dæns]", "verb", "elementary_level"),
        SimpleWordsModel("Drink", "İçmək", "[drɪŋk]", "verb", "elementary_level"),
        SimpleWordsModel("Hot", "İsti", "[hɒt]", "adjective", "elementary_level"),
        SimpleWordsModel("Old", "Qoca", "[oʊld]", "adjective", "elementary_level"),
        SimpleWordsModel("Play", "Oynamaq", "[pleɪ]", "verb", "elementary_level"),
        SimpleWordsModel("Elephant", "Fil", "[ˈɛlɪfənt]", "noun", "elementary_level"),
        SimpleWordsModel("Fish", "Balıq", "[fɪʃ]", "noun", "elementary_level"),
        SimpleWordsModel("House", "Ev", "[haʊs]", "noun", "elementary_level"),
        SimpleWordsModel("Juice", "Şirə", "[ʤuːs]", "noun", "elementary_level"),
        SimpleWordsModel("Kite", "Çərpələng", "[kaɪt]", "noun", "elementary_level"),
        SimpleWordsModel("Lion", "Şir", "[ˈlaɪən]", "noun", "elementary_level"),
        SimpleWordsModel("Mouse", "Siçan", "[maʊs]", "noun", "elementary_level"),
        SimpleWordsModel("Nose", "Burun", "[noʊz]", "noun", "elementary_level"),
        SimpleWordsModel("Orange", "Portağal", "[ˈɔrɪnʤ]", "noun", "elementary_level"),
        SimpleWordsModel("Queen", "Kraliça", "[kwiːn]", "noun", "elementary_level"),
        SimpleWordsModel("Rabbit", "Dovşan", "[ˈræbɪt]", "noun", "elementary_level"),
        SimpleWordsModel("Sun", "Günəş", "[sʌn]", "noun", "elementary_level"),
        SimpleWordsModel("Tree", "Ağac", "[triː]", "noun", "elementary_level"),
    )

    val listOfIntermediateWords = mutableListOf(
        SimpleWordsModel("Community", "Toplum", "[kəˈmjuːnəti]", "noun", "intermediate_level"),
        SimpleWordsModel("Random", "Təsadüfi", "[ˈrændəm]", "adjective", "intermediate_level"),
        SimpleWordsModel("Range", "Aralıq", "[reɪndʒ]", "noun", "intermediate_level"),
        SimpleWordsModel("Reinforce", "Təqviyə", "[ˌriːɪnˈfɔːrs]", "verb", "intermediate_level"),
        SimpleWordsModel("Reject", "Ləğv", "[rɪˈdʒekt]", "verb", "intermediate_level"),
        SimpleWordsModel("Release", "Buraxmaq", "[rɪˈliːs]", "verb", "intermediate_level"),
        SimpleWordsModel("Reliable", "Etibarlı", "[rɪˈlaɪəbl]", "adjective", "intermediate_level"),
        SimpleWordsModel("Resident", "Sakin", "[ˈrezɪdənt]", "noun", "intermediate_level"),
        SimpleWordsModel("Restrain", "Saxlamaq", "[rɪˈstreɪn]", "verb", "intermediate_level"),
        SimpleWordsModel("Restrict", "Məhdudlaşdırmaq", "[rɪˈstrɪkt]", "verb", "intermediate_level"),
        SimpleWordsModel("Reveal", "Aşkar", "[rɪˈviːl]", "verb", "intermediate_level"),
        SimpleWordsModel("Visdom", "Müdrik", "[ˈwɪzdəm]", "noun", "intermediate_level"),
        SimpleWordsModel("Simulate", "Təqlid", "[ˈsɪmjuleɪt]", "verb", "intermediate_level"),
        SimpleWordsModel("Solar", "Günəşli", "[ˈsoʊlər]", "adjective", "intermediate_level"),
        SimpleWordsModel("Specify", "Müəyyənləşdirmək", "[ˈspesɪfaɪ]", "verb", "intermediate_level"),
        SimpleWordsModel("Dot", "Nöqtə", "[dɒt]", "noun", "intermediate_level"),
        SimpleWordsModel("Reverse", "Tərs", "[rɪˈvɜːrs]", "verb", "intermediate_level"),
        SimpleWordsModel("Straight", "Düz", "[streɪt]", "adjective", "intermediate_level"),
        SimpleWordsModel("Injury", "Zədə", "[ˈɪndʒəri]", "noun", "intermediate_level"),
        SimpleWordsModel("Suspend", "Dayandırmaq", "[səˈspend]", "verb", "intermediate_level"),
        SimpleWordsModel("Universe", "Kainat", "[ˈjuːnɪvɜːrs]", "noun", "intermediate_level"),
        SimpleWordsModel("Target", "Hədəf", "[ˈtɑːrɡɪt]", "noun", "intermediate_level"),
        SimpleWordsModel("Terminate", "Bitirmək", "[ˈtɜːrmɪneɪt]", "verb", "intermediate_level"),
        SimpleWordsModel("Theme", "Mövzu", "[θiːm]", "noun", "intermediate_level"),
        SimpleWordsModel("Transition", "Keçid", "[trænˈzɪʃn]", "noun", "intermediate_level"),
        SimpleWordsModel("Transparent", "Şəffaf", "[trænsˈpærənt]", "adjective", "intermediate_level"),
        SimpleWordsModel("Trend", "İrəliləyiş", "[trend]", "noun", "intermediate_level"),
        SimpleWordsModel("Equal", "Bərabər", "[ˈiːkwəl]", "adjective", "intermediate_level"),
        SimpleWordsModel("Utilize", "İstifadə etmək", "[ˈjuːtəlaɪz]", "verb", "intermediate_level"),
        SimpleWordsModel("Vehicle", "Nəqliyyat", "[ˈviːəkl]", "noun", "intermediate_level"),
        SimpleWordsModel("Version", "Versiya", "[ˈvɜːrʒn]", "noun", "intermediate_level"),
        SimpleWordsModel("Via", "Vasitəsilə", "[ˈvaɪə]", "preposition", "intermediate_level"),
        SimpleWordsModel("Vision", "Görmə", "[ˈvɪʒn]", "noun", "intermediate_level"),
        SimpleWordsModel("Volume", "Həcm", "[ˈvɒljuːm]", "noun", "intermediate_level"),
        SimpleWordsModel("Whereas", "Halbuki", "[ˌweərˈæz]", "conjunction", "intermediate_level"),
        SimpleWordsModel("Widespread", "Geniş yayılmış", "[ˈwaɪdspred]", "adjective", "intermediate_level"),
        SimpleWordsModel("Yield", "Məhsul", "[jiːld]", "verb", "intermediate_level"),
        SimpleWordsModel("Abstract", "Mücərrəd", "[ˈæbstrækt]", "adjective", "intermediate_level"),
        SimpleWordsModel("Accumulate", "Toplamaq", "[əˈkjuːmjəleɪt]", "verb", "intermediate_level"),
        SimpleWordsModel("Append", "Əlavə etmək", "[əˈpend]", "verb", "intermediate_level"),
        SimpleWordsModel("Automate", "Avtomatlaşdırmaq", "[ˈɔːtəmeɪt]", "verb", "intermediate_level"),
        SimpleWordsModel("Bias", "Qərəzlik", "[ˈbaɪəs]", "noun", "intermediate_level"),
        SimpleWordsModel("Bulk", "Toplu", "[bʌlk]", "noun", "intermediate_level"),
        SimpleWordsModel("Cease", "Dayandırmaq", "[siːs]", "verb", "intermediate_level"),
        SimpleWordsModel("Concurrent", "Eyni", "[kənˈkʌrənt]", "adjective", "intermediate_level"),
        SimpleWordsModel("Confirm", "Təstiq etmək", "[kənˈfɜːrm]", "verb", "intermediate_level"),
        SimpleWordsModel("Contemporary", "Müasir", "[kənˈtemprəri]", "adjective", "intermediate_level"),
        SimpleWordsModel("Contradiction", "Ziddiyyət", "[ˌkɒntrəˈdɪkʃn]", "noun", "intermediate_level"),
        SimpleWordsModel("Converse", "Müzakirə", "[kənˈvɜːrs]", "verb", "intermediate_level"),
        SimpleWordsModel("Convey", "Ötürmək", "[kənˈveɪ]", "verb", "intermediate_level"),
        SimpleWordsModel("Defect", "Qüsur", "[ˈdiːfekt]", "noun", "intermediate_level"),
        SimpleWordsModel("Deficiency", "Çatışmamazlıq", "[dɪˈfɪʃnsi]", "noun", "intermediate_level"),
        SimpleWordsModel("Devise", "Hazırlamaq", "[dɪˈvaɪz]", "verb", "intermediate_level"),
        SimpleWordsModel("Destroy", "Dağıtmaq", "[dɪˈstrɔɪ]", "verb", "intermediate_level"),
        SimpleWordsModel("Duration", "Davametmə", "[djuˈreɪʃn]", "noun", "intermediate_level"),
        SimpleWordsModel("Define", "Müəyyənləşdirmək", "[dɪˈfaɪn]", "verb", "intermediate_level"),
        SimpleWordsModel("Excellent", "Möhtəşəm", "[ˈeksələnt]", "adjective", "intermediate_level"),
        SimpleWordsModel("Forgot", "Unutmaq", "[fəˈɡɒt]", "verb", "intermediate_level"),
        SimpleWordsModel("Frost", "Şaxta", "[frɒst]", "noun", "intermediate_level"),
        SimpleWordsModel("Framework", "Çərçivə", "[ˈfreɪmwɜːrk]", "noun", "intermediate_level"),
        SimpleWordsModel("Guideline", "Təlimat", "[ˈɡaɪdlaɪn]", "noun", "intermediate_level"),
        SimpleWordsModel("Hero", "Qəhrəman", "[ˈhɪərəʊ]", "noun", "intermediate_level"),
        SimpleWordsModel("Hypothesis", "Fərziyyə", "[haɪˈpɒθəsɪs]", "noun", "intermediate_level"),
        SimpleWordsModel("Immortal", "Ölümsüz", "[ɪˈmɔːtl]", "adjective", "intermediate_level"),
        SimpleWordsModel("Inspiration", "Ilham", "[ˌɪnspəˈreɪʃn]", "noun", "intermediate_level"),
        SimpleWordsModel("Infinity", "Sonsuzluq", "[ɪnˈfɪnəti]", "noun", "intermediate_level"),
        SimpleWordsModel("Isolate", "Təcrid", "[ˈaɪsəleɪt]", "verb", "intermediate_level"),
        SimpleWordsModel("Layer", "Qat", "[ˈleɪər]", "noun", "intermediate_level"),
        SimpleWordsModel("Medium", "Orta", "[ˈmiːdiəm]", "noun", "intermediate_level"),
        SimpleWordsModel("Walk", "Gəzmək", "[wɔːk]", "verb", "intermediate_level"),
        SimpleWordsModel("Swim", "Üzmək", "[swɪm]", "verb", "intermediate_level"),
        SimpleWordsModel("Wall", "Divar", "[wɔːl]", "noun", "intermediate_level"),
        SimpleWordsModel("Talk", "Danışmaq", "[tɔːk]", "verb", "intermediate_level"),
        SimpleWordsModel("Speak", "Danışmaq", "[spiːk]", "verb", "intermediate_level"),
        SimpleWordsModel("Listen", "Dinləmək", "[ˈlɪsən]", "verb", "intermediate_level"),
        SimpleWordsModel("Write", "Yazmaq", "[raɪt]", "verb", "intermediate_level"),
        SimpleWordsModel("Understand", "Anlamaq", "[ˌʌndəˈstænd]", "verb", "intermediate_level")
    )

    var listOfAdvanceWordsForVocabulary = listOf(
        SimpleWordsModel("Abate", "Azalma", "[əˈbeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Abhor", "Nifrət", "[əbˈhɔːr]", "verb", "advance_level"),
        SimpleWordsModel("Accolade", "Tərif", "[ˈækəˌleɪd]", "noun", "advance_level"),
        SimpleWordsModel("Acrimonious", "Kəskin", "[ˌækrəˈmoʊniəs]", "adjective", "advance_level"),
        SimpleWordsModel("Acumen", "Idrak", "[ˈækjʊmən]", "noun", "advance_level"),
        SimpleWordsModel("Admonish", "Bənzərsiz", "[ədˈmɒnɪʃ]", "verb", "advance_level"),
        SimpleWordsModel("Adulation", "Tərif", "[ˌædʒʊˈleɪʃən]", "noun", "advance_level"),
        SimpleWordsModel("Adversity", "Müsibət", "[ədˈvɜːrsɪti]", "noun", "advance_level"),
        SimpleWordsModel("Aesthetic", "Estetik", "[iːsˈθetɪk]", "adjective", "advance_level"),
        SimpleWordsModel("Affable", "Mehriban", "[ˈæfəbl]", "adjective", "advance_level"),
        SimpleWordsModel("Affluent", "Varlı", "[ˈæfluənt]", "adjective", "advance_level"),
        SimpleWordsModel("Aggrandize", "Böyütmək", "[əˈɡrændaɪz]", "verb", "advance_level"),
        SimpleWordsModel("Alacrity", "Cəldlik", "[əˈlækrɪti]", "noun", "advance_level"),
        SimpleWordsModel("Altruistic", "Fədakar", "[ˌæltruˈɪstɪk]", "adjective", "advance_level"),
        SimpleWordsModel("Amalgamate", "Birləşmək", "[əˈmælɡəmeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Ambivalent", "İkitərəfli", "[æmˈbɪvələnt]", "adjective", "advance_level"),
        SimpleWordsModel("Ameliorate", "Yaxşılaşdırmaq", "[əˈmiːljəˌreɪt]", "verb", "advance_level"),
        SimpleWordsModel("Analogous", "Analoji", "[əˈnæləɡəs]", "adjective", "advance_level"),
        SimpleWordsModel("Apathetic", "Laqeyd", "[ˌæpəˈθɛtɪk]", "adjective", "advance_level"),
        SimpleWordsModel("Appease", "Sakitləşdirmək", "[əˈpiːz]", "verb", "advance_level"),
        SimpleWordsModel("Arbitrary", "İxtiyari", "[ˈɑːrbɪtrəri]", "adjective", "advance_level"),
        SimpleWordsModel("Arcane", "Gizli", "[ɑːrˈkeɪn]", "adjective", "advance_level"),
        SimpleWordsModel("Ardent", "Alovlu", "[ˈɑːrdənt]", "adjective", "advance_level"),
        SimpleWordsModel("Arduous", "Çətin", "[ˈɑːdjuəs]", "adjective", "advance_level"),
        SimpleWordsModel("Assiduous", "Çalışqan", "[əˈsɪdjuəs]", "adjective", "advance_level"),
        SimpleWordsModel("Astute", "Zəkalı", "[əˈstjuːt]", "adjective", "advance_level"),
        SimpleWordsModel("Attenuate", "Zəiflətmək", "[əˈtɛnjʊeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Audacious", "Cəsarətli", "[ɔːˈdeɪʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Augment", "Artırmaq", "[ɔːɡˈmɛnt]", "verb", "advance_level"),
        SimpleWordsModel("Auspicious", "Xeyirli", "[ɔːˈspɪʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Austere", "Sərt", "[ɔːˈstɪə]", "adjective", "advance_level"),
        SimpleWordsModel("Autonomous", "Muxtar", "[ɔːˈtɒnəməs]", "adjective", "advance_level"),
        SimpleWordsModel("Avarice", "Xəsis", "[ˈævərɪs]", "noun", "advance_level"),
        SimpleWordsModel("Benevolent", "Xeyirxah", "[bəˈnɛvələnt]", "adjective", "advance_level"),
        SimpleWordsModel("Benign", "Xeyirxah", "[bɪˈnaɪn]", "adjective", "advance_level"),
        SimpleWordsModel("Buttress", "Bağlayıcı", "[ˈbʌtrɪs]", "noun", "advance_level"),
        SimpleWordsModel("Callous", "Mərhəmətsiz", "[ˈkæləs]", "adjective", "advance_level"),
        SimpleWordsModel("Candor", "Açıq-aşkar", "[ˈkændə]", "noun", "advance_level"),
        SimpleWordsModel("Capricious", "Şıltaq", "[kəˈprɪʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Censure", "Qınaq", "[ˈsɛnʃər]", "verb", "advance_level"),
        SimpleWordsModel("Chicanery", "Dələduzluq", "[ʃɪˈkeɪnəri]", "noun", "advance_level"),
        SimpleWordsModel("Circumscribe", "Məhdud", "[ˈsɜːkəmskraɪb]", "verb", "advance_level"),
        SimpleWordsModel("Circumspect", "Ehtiyatlı", "[ˈsɜːkəmspekt]", "adjective", "advance_level"),
        SimpleWordsModel("Clandestine", "Gizli", "[klænˈdɛstɪn]", "adjective", "advance_level"),
        SimpleWordsModel("Coalesce", "Birləşmək", "[ˌkəʊəˈlɛs]", "verb", "advance_level"),
        SimpleWordsModel("Cogent", "İnandırıcı", "[ˈkəʊdʒənt]", "adjective", "advance_level"),
        SimpleWordsModel("Commensurate", "Mütənasib", "[kəˈmɛnsjʊrət]", "adjective", "advance_level"),
        SimpleWordsModel("Complacent", "Özündən razı", "[kəmˈpleɪsənt]", "adjective", "advance_level"),
        SimpleWordsModel("Conciliatory", "Barışdırıcı", "[kənˈsɪliətəri]", "adjective", "advance_level"),
        SimpleWordsModel("Confluence", "Birləşmə", "[ˈkɒnflʊəns]", "noun", "advance_level"),
        SimpleWordsModel("Conflagration", "Yanğın", "[ˌkɒnfləˈɡreɪʃən]", "noun", "advance_level"),
        SimpleWordsModel("Conjecture", "Zənn", "[kənˈdʒɛkʧər]", "noun", "advance_level"),
        SimpleWordsModel("Consternation", "Çaşqınlıq", "[ˌkɒnstəˈneɪʃən]", "noun", "advance_level"),
        SimpleWordsModel("Construe", "Təfsir etmək", "[kənˈstruː]", "verb", "advance_level"),
        SimpleWordsModel("Contentious", "Mübahisəli", "[kənˈtɛnʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Contrite", "Təssüf", "[ˈkɒntraɪt]", "adjective", "advance_level"),
        SimpleWordsModel("Copious", "Bol", "[ˈkəʊpiəs]", "adjective", "advance_level"),
        SimpleWordsModel("Corroborate", "Təsdiq", "[kəˈrɒbəreɪt]", "verb", "advance_level"),
        SimpleWordsModel("Credulous", "Etibarlı", "[ˈkrɛdjʊləs]", "adjective", "advance_level"),
        SimpleWordsModel("Culpable", "Günahkar", "[ˈkʌlpəbl]", "adjective", "advance_level"),
        SimpleWordsModel("Dearth", "Çatışmamazlıq", "[dɜːθ]", "noun", "advance_level"),
        SimpleWordsModel("Debilitate", "Zəifləmə", "[dɪˈbɪlɪteɪt]", "verb", "advance_level"),
        SimpleWordsModel("Debunk", "İfşa", "[dɪˈbʌŋk]", "verb", "advance_level"),
        SimpleWordsModel("Decorum", "Ədəb", "[dɪˈkɔːrəm]", "noun", "advance_level"),
        SimpleWordsModel("Deference", "Ehtiram", "[ˈdɛfərəns]", "noun", "advance_level"),
        SimpleWordsModel("Deleterious", "Zərərli", "[ˌdɛləˈtɪərɪəs]", "adjective", "advance_level"),
        SimpleWordsModel("Demur", "Narazı olmaq", "[dɪˈmɜː]", "verb", "advance_level"),
        SimpleWordsModel("Denizen", "Sakin", "[ˈdɛnɪzən]", "noun", "advance_level"),
        SimpleWordsModel("Deride", "Lağ etmək", "[dɪˈraɪd]", "verb", "advance_level"),
        SimpleWordsModel("Derivative", "Törəmə", "[dɪˈrɪvətɪv]", "noun", "advance_level"),
        SimpleWordsModel("Diffident", "Özgüvənsiz", "[ˈdɪfɪdənt]", "adjective", "advance_level"),
        SimpleWordsModel("Dilatory", "Ləng", "[ˈdɪlətəri]", "adjective", "advance_level"),
        SimpleWordsModel("Disaffected", "Narazı", "[ˌdɪsəˈfɛktɪd]", "adjective", "advance_level"),
        SimpleWordsModel("Discern", "Fərqləndirən", "[dɪˈsɜːn]", "verb", "advance_level"),
        SimpleWordsModel("Discomfit", "Narahatlıq", "[dɪsˈkʌmfɪt]", "verb", "advance_level"),
        SimpleWordsModel("Disdain", "Nifrət etmək", "[dɪsˈdeɪn]", "verb", "advance_level"),
        SimpleWordsModel("Disingenuous", "Səmimi olmayan", "[ˌdɪsɪnˈdʒɛnjʊəs]", "adjective", "advance_level"),
        SimpleWordsModel("Disseminate", "Yaymaq", "[dɪˈsɛmɪneɪt]", "verb", "advance_level"),
        SimpleWordsModel("Distend", "Doldurulmuş", "[dɪˈstɛnd]", "verb", "advance_level"),
        SimpleWordsModel("Dormant", "Yatmış", "[ˈdɔːmənt]", "adjective", "advance_level"),
        SimpleWordsModel("Duress", "Məcbur etmək", "[djʊˈrɛs]", "noun", "advance_level"),
        SimpleWordsModel("Ebullient", "Qaynayan", "[ɪˈbʌljənt]", "adjective", "advance_level"),
        SimpleWordsModel("Edifice", "Bina", "[ˈɛdɪfɪs]", "noun", "advance_level"),
        SimpleWordsModel("Efficacy", "Effektivlik", "[ˈɛfɪkəsi]", "noun", "advance_level"),
        SimpleWordsModel("Elicit", "Aşkar etmək", "[ɪˈlɪsɪt]", "verb", "advance_level"),
        SimpleWordsModel("Elucidate", "Aydınlaşdırmaq", "[ɪˈluːsɪdeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Embellish", "Zinətləndirmək", "[ɪmˈbɛlɪʃ]", "verb", "advance_level"),
        SimpleWordsModel("Eminent", "Görkəmli olmaq", "[ˈɛmɪnənt]", "adjective", "advance_level"),
        SimpleWordsModel("Emulate", "Təqlid etmək", "[ˈɛmjʊleɪt]", "verb", "advance_level"),
        SimpleWordsModel("Engender", "Yaratmaq", "[ɪnˈdʒɛndə]", "verb", "advance_level"),
        SimpleWordsModel("Enigmatic", "Müəmmalı", "[ˌɛnɪɡˈmætɪk]", "adjective", "advance_level"),
        SimpleWordsModel("Equivocate", "İkimənalı", "[ɪˈkwɪvəkeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Erudite", "Savadlı", "[ˈɛrʊdaɪt]", "adjective", "advance_level"),
        SimpleWordsModel("Eulogy", "Tərifləmək", "[ˈjuːlədʒi]", "noun", "advance_level"),
        SimpleWordsModel("Evanescent", "Qurtarmaq", "[ˌɛvəˈnɛsənt]", "adjective", "advance_level"),
        SimpleWordsModel("Exacerbate", "Kəskinləşdirmək", "[ɪɡˈzæsəbeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Exculpate", "Bəraət", "[ˈɛkskəlpeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Exonerate", "Bəraət vermək", "[ɪɡˈzɒnəreɪt]", "verb", "advance_level"),
        SimpleWordsModel("Exorbitant", "Aşırı", "[ɪɡˈzɔːbɪtənt]", "adjective", "advance_level"),
        SimpleWordsModel("Expedient", "Məqsədəuyğun", "[ɪkˈspiːdiənt]", "adjective", "advance_level"),
        SimpleWordsModel("Extol", "Tərifləmək", "[ɪkˈstoʊl]", "verb", "advance_level"),
        SimpleWordsModel("Extraneous", "Kənar", "[ɪkˈstreɪniəs]", "adjective", "advance_level"),
        SimpleWordsModel("Extricate", "Azad", "[ˈɛkstrɪkeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Exult", "Sevinmək", "[ɪɡˈzʌlt]", "verb", "advance_level"),
        SimpleWordsModel("Facetious", "Zarafatçıl", "[fəˈsiːʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Fallacious", "Yanlış", "[fəˈleɪʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Fatuous", "Axmaq", "[ˈfæʧʊəs]", "adjective", "advance_level"),
        SimpleWordsModel("Feckless", "Məsuliyyətsiz", "[ˈfɛkləs]", "adjective", "advance_level"),
        SimpleWordsModel("Felicitous", "Uğurlu", "[fəˈlɪsɪtəs]", "adjective", "advance_level"),
        SimpleWordsModel("Fervid", "Qızğın", "[ˈfɜrvɪd]", "adjective", "advance_level"),
        SimpleWordsModel("Fetid", "İylənmiş", "[ˈfɛtɪd]", "adjective", "advance_level"),
        SimpleWordsModel("Florid", "Çiçəkli", "[ˈflɔrɪd]", "adjective", "advance_level"),
        SimpleWordsModel("Foment", "Qıcıqlandırmaq", "[ˈfoʊmɛnt]", "verb", "advance_level"),
        SimpleWordsModel("Frenetic", "Çılğın", "[frəˈnɛtɪk]", "adjective", "advance_level"),
        SimpleWordsModel("Garrulous", "Danışqan", "[ˈɡærələs]", "adjective", "advance_level"),
        SimpleWordsModel("Germane", "Uyğun", "[dʒɜːˈmeɪn]", "adjective", "advance_level"),
        SimpleWordsModel("Gregarious", "Ünsiyyətçil", "[ɡrɪˈɡɛərɪəs]", "adjective", "advance_level"),
        SimpleWordsModel("Guile", "Hiylə", "[ɡaɪl]", "noun", "advance_level"),
        SimpleWordsModel("Hegemony", "Hegemonluq", "[hɪˈɡɛməni]", "noun", "advance_level"),
        SimpleWordsModel("Heretic", "Bidətçi", "[ˈhɛrɪtɪk]", "noun", "advance_level"),
        SimpleWordsModel("Hiatus", "Fasilə", "[haɪˈeɪtəs]", "noun", "advance_level"),
        SimpleWordsModel("Hierarchy", "İyerarxiya", "[ˈhaɪərɑrki]", "noun", "advance_level"),
        SimpleWordsModel("Ignominious", "Alçaq", "[ˌɪɡnəˈmɪniəs]", "adjective", "advance_level"),
        SimpleWordsModel("Immutable", "Dəyişməz", "[ɪˈmjuːtəbl]", "adjective", "advance_level"),
        SimpleWordsModel("Imperious", "Hökmlü", "[ɪmˈpɪəriəs]", "adjective", "advance_level"),
        SimpleWordsModel("Implacable", "Barışmaz", "[ɪmˈplækəbl]", "adjective", "advance_level"),
        SimpleWordsModel("Impugn", "Mübahisəli", "[ɪmˈpjuːn]", "verb", "advance_level"),
        SimpleWordsModel("Indolent", "Tənbəl", "[ˈɪndələnt]", "adjective", "advance_level"),
        SimpleWordsModel("Innocuous", "Məsum", "[ɪˈnɒkjuəs]", "adjective", "advance_level"),
        SimpleWordsModel("Insipid", "Zövqsüz", "[ɪnˈsɪpɪd]", "adjective", "advance_level"),
        SimpleWordsModel("Invective", "Təhqiramiz", "[ɪnˈvɛktɪv]", "noun", "advance_level"),
        SimpleWordsModel("Irascible", "Əsəbi", "[ɪˈræsəbl]", "adjective", "advance_level"),
        SimpleWordsModel("Itinerant", "Səyahətçi", "[aɪˈtɪnərənt]", "adjective", "advance_level"),
        SimpleWordsModel("Lassitude", "Yorğunluq", "[ˈlæsɪtuːd]", "noun", "advance_level"),
        SimpleWordsModel("Latent", "Gizli", "[ˈleɪtənt]", "adjective", "advance_level"),
        SimpleWordsModel("Loquacious", "Danışqan", "[ləˈkweɪʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Lucid", "Aydın", "[ˈluːsɪd]", "adjective", "advance_level"),
        SimpleWordsModel("Luminous", "Işıqlı", "[ˈluːmɪnəs]", "adjective", "advance_level"),
        SimpleWordsModel("Mendacious", "Xəyanətkar", "[mɛnˈdeɪʃəs]", "adjective", "advance_level"),
        SimpleWordsModel("Meticulous", "Vasvası", "[məˈtɪkjʊləs]", "adjective", "advance_level"),
        SimpleWordsModel("Misanthrope", "Misantrop", "[ˈmɪzənˌθroʊp]", "noun", "advance_level"),
        SimpleWordsModel("Mitigate", "Yumşaltmaq", "[ˈmɪtɪˌɡeɪt]", "verb", "advance_level"),
        SimpleWordsModel("Mollify", "Yumşaltmaq", "[ˈmɒlɪfaɪ]", "verb", "advance_level"),
        SimpleWordsModel("Munificent", "Əliaçıq", "[mjuːˈnɪfɪsənt]", "adjective", "advance_level")
    )
}



